include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-package/npm-deployment.yml'

stages:
  - build
  - deploy

build-package:
  stage: build
  image: ${WEB_BUILD_IMAGE_NAME}:${WEB_BUILD_IMAGE_TAG}
  variables:
    WEB_BUILD_IMAGE_NAME: registry.gitlab.com/redmic-project/docker/web-build
    WEB_BUILD_IMAGE_TAG: latest
  before_script:
    - type yarn grunt
    - yarn install
  script:
    - grunt
  dependencies: []
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    expire_in: 1 week
    paths:
      - dist/
  cache:
    paths:
      - node_modules/
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
